global:
  app_name: cicd-deployment

replicaCount: 3

image:
  repository: bisshwajitsamanta/cicd
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
  targetPort: 65530
